#!/bin/bash

whereiam=$(dirname $0)
appname=mtimer
def_time_file=$whereiam/.${appname}_def_time

if [ -f $def_time_file ]
then
	def_time=$(cat $def_time_file)
else
	def_time=60
fi

unix=$(uname)

if [ $unix == "Linux" ]
then
	CheckBeep=$(which beep)
	if [ -z $CheckBeep ]
	then
		clear
		echo "Install 'beep' and activate:"
		echo
		echo "	sudo apt install beep && modprobe pcspkr"
		echo
	else
	if [ -z $1 ]
	then
                time=$def_time
                clear
                while [ $time -ge 1 ]
                do
                        clear
                        echo "Timer set to default ($def_time seconds)."
                        echo
                        echo "$time second(s)..."
                        time=$((time-1))
                        sleep 1
                done
                i=1
                while [ $i -le 4 ]
                do
                        beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.6
                        i=$((i+1))
                done
	else
		clear
		case $1 in
		--help)
			clear
			echo "Usage:"
			echo 
			echo "Help page" 
			echo "	$appname --help"
			echo "Set default timer value to N seconds"
			echo "	$appname --set-default N"
			echo "Set timer to N minutes" 
			echo "	$appname --minute N"
			echo "	$appname -m N"
			echo "Set timer to N hours"
			echo "	$appname --hour N"
			echo "	$appname -h N"
			echo "Start with default timer value"
			echo "(Default timer value is 60 seconds)."
			echo "	$appname"
			echo 
			echo "Version 0.1.1."
			echo "Last modified ks 13 jan 2020."
			echo "Free to modify, use, and distribute."
			;;
		--set-default)
			if [ -z $2 ]
			then
				clear
				echo "Enter default timer value in seconds."
				echo
			else
				echo $2 > $def_time_file
				clear
				echo "Default timer value set to $2 second(s)."
				echo
			fi
			;;
		--minute|-m)
			if [ -z $2 ]
			then
				clear
				echo "Enter timer value in minutes."
				echo
			else
				minute_time=$2
				float_time=$(echo "60*$minute_time" | bc)
				time=${float_time%.*}
				clear 
				while [ $time -ge 1 ]
				do
					clear
					echo "Timer set to $minute_time minute(s)."
					echo
					echo "$time second(s)..."
					time=$((time-1))
					sleep 1
				done
				i=1
				while [ $i -le 4 ]
				do
					beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.6
					i=$((i+1))
				done
			fi
			;;
		--hour|-h)
			if [ -z $2 ]
			then
				clear
				echo "Enter timer value in hours."
				echo
			else
				hour_time=$2
	                	float_time=$(echo "3600*$hour_time" | bc)
				time=${float_time%.*}
	                	clear 
	                	while [ $time -ge 1 ] 
	                	do
	                	        clear
	                	        echo "Timer set to $hour_time hour(s)."
	                	        echo
	                	        echo "$time second(s)..."
	                	        time=$((time-1))
	                	        sleep 1
	                	done
	                	i=1
	                	while [ $i -le 4]
	                	do
	                	        beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.6 
	                	        i=$((i+1))
	                	done
			fi
			;;
		*)
			time=$1
			clear
			while [ $time -ge 1 ]
			do
				clear
				echo "Timer set to $1 second(s)."
				echo
				echo "$time second(s)..."
				time=$((time-1))
				sleep 1
			done
	                i=1
	                while [ $i -le 4 ]
	                do
	                        beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.6 
	                        i=$((i+1))
	                done
			;;
		esac
	fi
	fi
else	
	if [ -z $1 ]
	then
	        time=$def_time
                clear
                while [ $time -ge 1 ]
                do
                        clear
                        echo "Timer set to default ($def_time seconds)."
                        echo
                        echo "$time second(s)..."
                        time=$((time-1))
                        sleep 1
                done
                i=1
                while [ $i -le 4 ]
                do
                        beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.05 ; beep ; sleep 0.6
                        i=$((i+1))
                done
        else
		case $1 in
		--help)
			clear
			echo "Usage:"
			echo 
			echo "Help page" 
			echo "	$appname --help"
			echo "Set default timer value to N seconds"
			echo "	$appname --set-default N"
			echo "Set timer to N minutes" 
			echo "	$appname --minute N"
			echo "	$appname -m N"
			echo "Set timer to N hours"
			echo "	$appname --hour N"
			echo "	$appname -h N"
			echo "Start with default timer value"
			echo "(Default timer value is 60 seconds)."
			echo "	$appname"
			echo 
			echo "Version 0.1.1."
			echo "Last modified ks 13 jan 2020."
			echo "Free to modify, use, and distribute."
			;;
		--set-default)
			if [ -z $2 ]
			then
				clear
				echo "Enter default timer value in seconds."
				echo
			else
				echo $2 > $def_time_file
				clear
				echo "Default timer value set to $2 second(s)."
				echo
			fi
			;;
		--minute|-m)
			if [ -z $2 ]
			then
				clear
				echo "Enter timer value in minutes."
				echo
			else
				minute_time=$2
				float_time=$(echo "60*$minute_time" | bc)
				time=${float_time%.*}
				clear 
				while [ $time -ge 1 ]
				do
					clear
					echo "Timer set to $minute_time minute(s)."
					echo
					echo "$time second(s)..."
					time=$((time-1))
					sleep 1
				done
				i=1
				while [ $i -le 4 ]
				do
					printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.6
					i=$((i+1))
				done
			fi
			;;
		--hour|-h)
			if [ -z $2 ]
			then
				clear
				echo "Enter timer value in hours."
				echo
			else
				hour_time=$2
	                	float_time=$(echo "3600*$hour_time" | bc)
				time=${float_time%.*}
	                	clear 
	                	while [ $time -ge 1 ] 
	                	do
	                	        clear
	                	        echo "Timer set to $hour_time hour(s)."
	                	        echo
	                	        echo "$time second(s)..."
	                	        time=$((time-1))
	                	        sleep 1
	                	done
	                	i=1
	                	while [ $i -le 4]
	                	do
	                	        printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.6 
	                	        i=$((i+1))
	                	done
			fi
			;;
		*)
			time=$1
			clear
			while [ $time -ge 1 ]
			do
				clear
				echo "Timer set to $1 second(s)."
				echo
				echo "$time second(s)..."
				time=$((time-1))
				sleep 1
			done
	                i=1
	                while [ $i -le 4 ]
	                do
	                        printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.15 ; printf "\a" ; sleep 0.6 
	                        i=$((i+1))
	                done
			;;
		esac
	fi
fi
