#!/bin/bash

CheckBeep=$(which beep)

if [ -z $CheckBeep ]
then
	echo "Install 'beep' and activate:"
	echo
	echo "	sudo apt install beep && modprobe pcspkr"
	echo
else

clear

if [ -z $1 ]
then
	time=60
	while [ $time -ge 1 ]
	do
		clear
		echo "Default timer setting is 1 minute."
		echo "=================================="
		echo
		echo $time
		time=$((time-1))
		sleep 1
	done
else
	time=$1
	while [ $time -ge 1 ]
	do
		clear
		echo "Timer set to $1 second(s)."
		echo "=========================="
		echo
		echo $time
		time=$((time-1))
		sleep 1
	done
fi


i=1

while [ $i -le 4 ]
do
        beep
        sleep 0.05
        beep
        sleep 0.05
        beep    
        sleep 0.05
        beep
        sleep 0.6
        i=$((i+1))
done

fi
